package datageneration.fields;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.apache.commons.lang3.text.WordUtils;

import java.util.Random;

@Getter
@AllArgsConstructor
public enum Country {
    ITALY("IT", "Italia", "0"), // 0 as country code as placeholder

    AFGHANISTAN("AF", "Afghanistan", "200"),
    ALBANIA("AL", "Albania", "100"),
    ALGERIA("DZ", "Algeria", "301"),
    ANDORRA("AD", "Andorra", "101"),
    ANGOLA("AO", "Angola", "302"),
    ANTIGUA_AND_BARBUDA("AG", "Antigua e Barbuda", "532"),
    SAUDI_ARABIA("SA", "Arabia Saudita", "203"),
    ARGENTINA("AR", "Argentina", "600"),
    AUSTRALIA("AU", "Australia", "700"),
    AUSTRIA("AT", "Austria", "102"),
    BAHAMAS("BS", "Bahamas", "502"),
    BAHRAIN("BH", "Bahrein", "204"),
    BANGLADESH("BD", "Bangladesh", "249"),
    BARBADOS("BB", "Barbados", "522"),
    BELGIUM("BE", "Belgio", "103"),
    BELIZE("BZ", "Belize", "512"),
    BENIN("BJ", "Benin", "314"),
    BHUTAN("BT", "Bhutan", "205"),
    BELARUS("BY", "Bielorussia", "139"),
    BOLIVIA("BO", "Bolivia", "601"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bosnia ed Erzegovina", "153"),
    BOTSWANA("BW", "Botswana", "358"),
    BRAZIL("BR", "Brasile", "602"),
    BRUNEI("BN", "Brunei", "207"),
    BULGARIA("BG", "Bulgaria", "104"),
    BURKINA_FASO("BF", "Burkina Faso", "354"),
    BURUNDI("BI", "Burundi", "305"),
    CAMBODIA("KH", "Cambogia", "208"),
    CAMEROON("CM", "Camerun", "306"),
    CANADA("CA", "Canada", "401"),
    CAPE_VERDE("CV", "Capo Verde", "307"),
    CHAD("TD", "Ciad", "309"),
    CHILE("CL", "Cile", "603"),
    CYPRUS("CY", "Cipro", "211"),
    COLOMBIA("CO", "Colombia", "604"),
    COMOROS("KM", "Comore", "310"),
    NORTH_KOREA("KP", "Corea del Nord", "214"),
    SOUTH_KOREA("KR", "Corea del Sud", "213"),
    COSTA_RICA("CR", "Costa Rica", "503"),
    CROATIA("HR", "Croazia", "149"),
    CUBA("CU", "Cuba", "504"),
    DENMARK("DK", "Danimarca", "107"),
    DOMINICA("DM", "Dominica", "526"),
    ECUADOR("EC", "Ecuador", "605"),
    EGYPT("EG", "Egitto", "336"),
    EL_SALVADOR("SV", "El Salvador", "506"),
    UNITED_ARAB_EMIRATES("AE", "Emirati Arabi Uniti", "215"),
    ERITREA("ER", "Eritrea", "368"),
    ESTONIA("EE", "Estonia", "144"),
    ETHIOPIA("ET", "Etiopia", "315"),
    PHILIPPINES("PH", "Filippine", "216"),
    FINLAND("FI", "Finlandia", "109"),
    FRANCE("FR", "Francia", "110"),
    GABON("GA", "Gabon", "316"),
    GAMBIA("GM", "Gambia", "317"),
    GERMANY("DE", "Germania", "112"),
    GHANA("GH", "Ghana", "318"),
    JAMAICA("JM", "Giamaica", "507"),
    JAPAN("JP", "Giappone", "219"),
    GIBRALTAR("GI", "Gibilterra", "113"),
    DJIBOUTI("DJ", "Gibuti", "361"),
    JORDAN("JO", "Giordania", "220"),
    GREECE("GR", "Grecia", "115"),
    GRENADA("GD", "Grenada", "524"),
    GREENLAND("GL", "Groenlandia", "402"),
    GUADELOUPE("GP", "Guadalupa", "508"),
    GUATEMALA("GT", "Guatemala", "509"),
    GUINEA("GN", "Guinea", "319"),
    EQUATORIAL_GUINEA("GQ", "Guinea Equatoriale", "321"),
    GUYANA("GY", "Guyana", "606"),
    HAITI("HT", "Haiti", "510"),
    HONDURAS("HN", "Honduras", "511"),
    INDIA("IN", "India", "222"),
    INDONESIA("ID", "Indonesia", "223"),
    IRAN("IR", "Iran", "224"),
    IRAQ("IQ", "Iraq", "225"),
    IRELAND("IE", "Irlanda", "116"),
    ICELAND("IS", "Islanda", "117"),
    ISRAEL("IL", "Israele", "226"),
    KENYA("KE", "Kenya", "322"),
    KIRIBATI("KI", "Kiribati", "731"),
    KOSOVO("XK", "Kosovo", "160"),
    KUWAIT("KW", "Kuwait", "227"),
    LAOS("LA", "Laos", "228"),
    LESOTHO("LS", "Lesotho", "359"),
    LATVIA("LV", "Lettonia", "145"),
    LEBANON("LB", "Libano", "229"),
    LIBERIA("LR", "Liberia", "325"),
    LIBYA("LY", "Libia", "326"),
    LIECHTENSTEIN("LI", "Liechtenstein", "119"),
    LITHUANIA("LT", "Lituania", "146"),
    LUXEMBOURG("LU", "Lussemburgo", "120"),
    MADAGASCAR("MG", "Madagascar", "327"),
    MALAWI("MW", "Malawi", "328"),
    MALDIVES("MV", "Maldive", "232"),
    MALI("ML", "Mali", "329"),
    MALTA("MT", "Malta", "121"),
    MOROCCO("MA", "Marocco", "330"),
    MARTINIQUE("MQ", "Martinica", "513"),
    MAURITANIA("MR", "Mauritania", "331"),
    MEXICO("MX", "Messico", "514"),
    MOLDOVA("MD", "Moldavia", "140"),
    MONACO("MC", "Monaco", "123"),
    MONGOLIA("MN", "Mongolia", "233"),
    MONTENEGRO("ME", "Montenegro", "159"),
    MONTSERRAT("MS", "Montserrat", "531"),
    MOZAMBIQUE("MZ", "Mozambico", "333"),
    NAMIBIA("NA", "Namibia", "300"),
    NAURU("NR", "Nauru", "713"),
    NEPAL("NP", "Nepal", "234"),
    NICARAGUA("NI", "Nicaragua", "515"),
    NIGER("NE", "Niger", "334"),
    NIGERIA("NG", "Nigeria", "335"),
    NORWAY("NO", "Norvegia", "125"),
    NEW_ZEALAND("NZ", "Nuova Zelanda", "719"),
    OMAN("OM", "Oman", "235"),
    NETHERLANDS("NL", "Paesi Bassi", "126"),
    PAKISTAN("PK", "Pakistan", "236"),
    PALAU("PW", "Palau", "734"),
    PANAMA("PA", "Panama", "516"),
    PAPUA_NEW_GUINEA("PG", "Papua Nuova Guinea", "730"),
    PARAGUAY("PY", "Paraguay", "610"),
    POLAND("PL", "Polonia", "127"),
    PORTUGAL("PT", "Portogallo", "128"),
    QATAR("QA", "Qatar", "237"),
    UNITED_KINGDOM("GB", "Regno Unito", "114"),
    DOMINICAN_REPUBLIC("DO", "Repubblica Dominicana", "505"),
    ROMANIA("RO", "Romania", "129"),
    RWANDA("RW", "Ruanda", "338"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts e Nevis", "533"),
    SAINT_LUCIA("LC", "Saint Lucia", "527"),
    SAINT_VINCENT_AND_GRENADINES("VC", "Saint Vincent e Grenadine", "528"),
    SAMOA("WS", "Samoa", "726"),
    SAN_MARINO("SM", "San Marino", "130"),
    SENEGAL("SN", "Senegal", "343"),
    SERBIA("RS", "Serbia", "158"),
    SIERRA_LEONE("SL", "Sierra Leone", "344"),
    SINGAPORE("SG", "Singapore", "248"),
    SYRIA("SY", "Siria", "240"),
    SLOVAKIA("SK", "Slovacchia", "155"),
    SLOVENIA("SI", "Slovenia", "150"),
    SOMALIA("SO", "Somalia", "345"),
    SPAIN("ES", "Spagna", "131"),
    SRI_LANKA("LK", "Sri Lanka", "209"),
    SUDAN("SD", "Sudan", "348"),
    SURINAME("SR", "Suriname", "608"),
    SWEDEN("SE", "Svezia", "132"),
    SWITZERLAND("CH", "Svizzera", "133"),
    TAIWAN("TW", "Taiwan", "217"),
    TANZANIA("TZ", "Tanzania", "357"),
    PALESTINIAN_TERRITORIES("PS", "Territori palestinesi", "161"),
    THAILAND("TH", "Thailandia", "241"),
    TOGO("TG", "Togo", "351"),
    TONGA("TO", "Tonga", "728"),
    TRINIDAD_AND_TOBAGO("TT", "Trinidad e Tobago", "612"),
    TUNISIA("TN", "Tunisia", "352"),
    TURKEY("TR", "Turchia", "243"),
    TUVALU("TV", "Tuvalu", "732"),
    UKRAINE("UA", "Ucraina", "138"),
    UGANDA("UG", "Uganda", "353"),
    HUNGARY("HU", "Ungheria", "134"),
    URUGUAY("UY", "Uruguay", "613"),
    VANUATU("VU", "Vanuatu", "733"),
    VENEZUELA("VE", "Venezuela", "614"),
    VIETNAM("VN", "Vietnam", "251"),
    YEMEN("YE", "Yemen", "246"),
    ZAMBIA("ZM", "Zambia", "355"),
    ZIMBABWE("ZW", "Zimbabwe", "337");

    private final String value, text, countryCode;

    private static final Random RANDOM = new Random();

    @Override
    public String toString() {
        return WordUtils.capitalizeFully(text);
    }

    public static Country getRandomNonItalyValue() {
        Country country;
        do {
            country = getRandomValue();
        } while (ITALY.equals(country));

        return country;
    }

    public static Country getRandomValue() {
        Country[] values = Country.values();
        return values[RANDOM.nextInt(values.length)];
    }
}